pipelines:
  branches:
    master:
      - step:
          name: Deploy to server rspmc - ehealthsys-simulasi
          trigger: automatic
          deployment: staging_RSPMC
          script:
            - echo "Deploying to server rspmc - ehealthsys-simulasi"
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: $HOST_USER
                SERVER: $HOST_ADDRESS
                PORT: $HOST_PORT
                MODE: 'script'
                COMMAND: './autodeploycicd/deployserver_rspmc_staging.sh'