pipelines:
  branches:
    rsip:
      - step:
          name: Deploy to server IP 4 - ihospital-rsip-simulasi
          trigger: automatic
          deployment: staging_RSIP
          script:
            - echo "Deploying to server IP 4 - ihospital-rsip-simulasi"
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: $HOST_USER
                SERVER: $HOST_ADDRESS
                PORT: $HOST_PORT
                MODE: 'script'
                COMMAND: './autodeploycicd/deployserver_rsip_staging.sh'