pipelines:
  branches:
    rsias:
      # - step:
      #     name: Deploy to server IP 3 RSIAS - ihospital-rsias-staging
      #     trigger: automatic
      #     deployment: staging_RSIAS
      #     script:
      #       - echo "Deploying to server on premise - ihospital-rsias-staging"
      #       - pipe: atlassian/ssh-run:0.2.2
      #         variables:
      #           SSH_USER: $HOST_USER
      #           SERVER: $HOST_ADDRESS
      #           PORT: $HOST_PORT
      #           MODE: "script"
      #           COMMAND: "./autodeploycicd/deployserver3_rsias_staging.sh"
      - step:
          name: Deploy to server IP 2 RSIAS - ihospital-rsias-staging
          trigger: automatic
          deployment: staging_RSIAS2
          script:
            - echo "Deploying to server on premise - ihospital-rsias-staging"
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: $HOST_USER
                SERVER: $HOST_ADDRESS
                PORT: $HOST_PORT
                MODE: "script"
                COMMAND: "./autodeploycicd/deployserver2_rsias_staging.sh"
