pipelines:
  branches:
    rsabe:
     - stage:
         name: Deploy to server IP 54 - ihospital-rsabe-simulasi
         deployment: staging_RSABE
         trigger: automatic
         steps:
          - step:
              script:
                - echo "Deploying to server IP 54 - ihospital-rsabe-simulasi"
                - pipe: atlassian/ssh-run:0.2.2
                  variables:
                    SSH_USER: $HOST_USER
                    SERVER: $HOST_ADDRESS
                    PORT: $HOST_PORT
                    MODE: 'script'
                    COMMAND: './autodeploycicd/deployserver_rsabe_staging.sh'