pipelines:
  branches:
    rswb: #Pipeline akan berjalan ketika ada merge atau push ke branch rswb
      - stage:
          name: Deploy to SERVER RSWB - e-asuransi-rswb-simulasi
          trigger: automatic
          deployment: staging_RSWB #environment akses public ssh server IP Private 192.168.214.223
          steps:
           - step:
              script:
                - echo "Deploy to server RSWB - e-asuransi-rswb-simulasi"
                - pipe: atlassian/ssh-run:0.2.2
                  variables:
                    SSH_USER: $HOST_USER #akses user login ssh server
                    SERVER: $HOST_ADDRESS #IP Public 
                    PORT: $HOST_PORT #Port SSH
                    MODE: 'script'
                    COMMAND: './autodeploycicd/deployserver_rswb_staging.sh' #SSH Pipelines akan menjalankan perintah Shell pada file
      - stage:
          name: Deploy to server RSWP - e-asuransi-simulasi
          trigger: automatic
          deployment: staging_RSWP #environment akses public ssh server IP Private 10.10.1.8
          steps:
           - step:
              script:
                - echo "Deploy to server RSWP - e-asuransi-simulasi"
                - pipe: atlassian/ssh-run:0.2.2
                  variables:
                    SSH_USER: $HOST_USER
                    SERVER: $HOST_ADDRESS
                    PORT: $HOST_PORT
                    MODE: 'script'
                    COMMAND: './autodeploycicd/deployserver_rswp_staging.sh'