pipelines:
  branches:
    rsnu:
      - step:
          name: Deploy to server ip 6 rsnu - ihospital-rsnu-simulasi
          trigger: automatic
          deployment: staging_RSNU
          script:
            - echo "Deploying to server ip 6 - repo ihospital-rsnu-simulasi"
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: $HOST_USER
                SERVER: $HOST_ADDRESS
                PORT: $HOST_PORT
                MODE: 'script'
                COMMAND: './autodeploycicd/deployserver_rsnu_staging.sh'