pipelines:
  branches:
    rsbkt_main:
      - step:
          name: Deploy to server IP 5 RSBKT - ihospital-rsbkt-simulasi
          trigger: automatic
          deployment: staging_RSBKT
          script:
            - echo "Deploying to server IP 5 RSBKT - ihospital-rsbkt-simulasi"
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: $HOST_USER
                SERVER: $HOST_ADDRESS
                PORT: $HOST_PORT
                MODE: 'script'
                COMMAND: './autodeploycicd/deployserver_rsbkt_staging.sh'