pipelines:
  branches:
    rscms_main:
      - step:
         name: Deploy to server IP 11 RSCMS - e-asuransi-rscms-simulasi
         trigger: automatic
         deployment: staging_RSCMS
         script:
           - echo "Deploying to server IP 11 RSCMS - e-asuransi-rscms-simulasi"
           - pipe: atlassian/ssh-run:0.2.2
             variables:
               SSH_USER: $HOST_USER
               SERVER: $HOST_ADDRESS
               PORT: $HOST_PORT
               MODE: 'script'
               COMMAND: './autodeploycicd/deployserver_rscms_staging.sh'