pipelines:
  branches:
    rsbri:
      - step:
          name: Deploy to server IP 100 RSBRI - repo website-rsbri
          trigger: automatic
          deployment: website_RSBRI
          script:
            - echo "Deploying to server IP 100 RSBRI - repo website-rsbri"
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: $HOST_USER
                SERVER: $HOST_ADDRESS
                PORT: $HOST_PORT
                MODE: 'script'
                COMMAND: './autodeploycicd/deployserver_rsbri_website.sh'