pipelines:
  branches:
    rsbri_simulasi:
      - step:
          name: Deploy to server IP 100 RSBRI - ihospital-rsbri-simulasi
          trigger: automatic
          deployment: staging_RSBRI
          script:
            - echo "Deploying to server IP 100 RSBRI - ihospital-rsbri-simulasi"
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: $HOST_USER
                SERVER: $HOST_ADDRESS
                PORT: $HOST_PORT
                MODE: 'script'
                COMMAND: './autodeploycicd/deployserver_rsbri_staging.sh'