pipelines:
  branches:
    rsaws:
      - step:
          name: Deploy to server 27 rsaws - rsaws-staging
          trigger: automatic
          deployment: staging_RSAWS
          script:
            - echo "Deploying to server 27 rsaws - rsaws-staging"
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: $HOST_USER
                SERVER: $HOST_ADDRESS
                PORT: $HOST_PORT
                MODE: 'script'
                COMMAND: './autodeploycicd/deployserver_rsaws_staging.sh'